CREATE TABLE notes (
	index SERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL,
	guild_id BIGINT NOT NULL,
	note TEXT NOT NULL,
	moderator BIGINT NOT NULL,
	timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
)
